Rename `standards` to `boilerplate`
...per team decision.

diff --git a/boilerplate/update b/boilerplate/update
--- a/boilerplate/update
+++ b/boilerplate/update
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
-# WARNING: THIS FILE IS MANAGED IN THE 'standardize' REPO AND COPIED TO OTHER REPOSITORIES.
-# ONLY EDIT THIS FILE FROM WITHIN THE 'standardize' REPOSITORY.
+# WARNING: THIS FILE IS MANAGED IN THE 'boilerplate' REPO AND COPIED TO OTHER REPOSITORIES.
+# ONLY EDIT THIS FILE FROM WITHIN THE 'boilerplate' REPOSITORY.
 # 
 # TO OPT OUT OF UPDATES, SEE THE README.
 
 # This script updates itself, and then re-execs itself if it has
-# changed. This is in case updates to standards rely on updates to this
+# changed. This is in case updates to conventions rely on updates to this
 # script.
 
 set -e
@@ -16,15 +16,15 @@ if [ "$1" ]; then
   OUT=$1
   # Let's make sure this was really a re-exec and not some other
   # weirdness.
-  if ! [[ -d "$OUT" ]] || ! diff -q "$0" "$OUT/standardize/standards/update"; then
+  if ! [[ -d "$OUT" ]] || ! diff -q "$0" "$OUT/boilerplate/boilerplate/update"; then
     echo "Something went wrong! I was invoked with '$OUT'!"
     exit 2
   fi
 else
   OUT="$(mktemp -d)"
-  git clone git@github.com:2uasimojo/standardize.git "${OUT}"
+  git clone git@gitlab.cee.redhat.com:service/boilerplate.git "${OUT}"
   echo "Updating the update script."
-  cp "${OUT}/standardize/standards/update" "$0"
+  cp "${OUT}/boilerplate/boilerplate/update" "$0"
   echo "Reinvoking..."
   echo ""
   exec "$0" "$OUT"
@@ -34,9 +34,9 @@ fi
 trap "rm -fr $OUT" EXIT
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
-# The directory in which this script lives is the STANDARDS_ROOT. Export
+# The directory in which this script lives is the CONVENTION_ROOT. Export
 # this for individual `update` scripts.
-export STANDARDS_ROOT=$DIR
+export CONVENTION_ROOT=$DIR
 
 # Allow this to be overridden by the environment, in case some bizarre
 # repo doesn't have an `origin` remote.
@@ -48,7 +48,7 @@ fi
 export REPO_ROOT=$(git rev-parse --show-toplevel)
 
 CONFIG_FILE="${DIR}/update.cfg"
-README="https://github.com/2uasimojo/standardize/blob/master/README.md"
+README="https://gitlab.cee.redhat.com/service/boilerplate/blob/master/README.md"
 
 if [ ! -f "$CONFIG_FILE" ]; then
   echo "$CONFIG_FILE not found."
@@ -74,10 +74,10 @@ while read directory junk; do
     exit 1
   fi
 
-  dir_path="${OUT}/standards/${directory}"
+  dir_path="${OUT}/boilerplate/${directory}"
   # Make sure the directory exists
   if ! [[ -d "$dir_path" ]]; then
-    echo "Invalid standards directory: '$directory'"
+    echo "Invalid convention directory: '$directory'"
     exit 1
   fi
 
